import React from 'react';
import { useState, useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { signIn } from "next-auth/react";

import GeneralLayout from '../components/layouts/generallayout';

import { Container, Row, Col, Button, Form } from 'react-bootstrap';
import doctorImage from "../images/doctor.jpg";
import Image from 'next/image';

import Calendar from 'react-calendar';
import NonSSRWrapper from '../components/nonssr/nonssr.component';
import { hashPassword } from '../lib/data-helper';
import { toast } from 'react-toastify';
import { sendEmail } from '../utils/email/email.util';

import clinicImage from "../images/clinic.png";



function Home() {


  const router = useRouter();





  return (
    <>
      <Head>
        <title>Sepaya Dental Clinic Scheduling System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Container>
        <Row>
          <Col xs="12">

            <div className="homeOuterWrapper">
              
              <div className="homeWrapper">
                <h1>Sepaya Dental Clinic</h1>
                <p><strong>Opening Hours:</strong> Monday to Saturday 8:00 am - 12:00 pm/1:00 pm - 5:00pm</p>
                
                <Image 
                  src={clinicImage}
                  alt="Clinic"
                  width={300}
                  height={300}
                />
              
             </div>  
            </div>
            
          
          </Col>

         
          


        </Row>
      </Container>  
      
    
    </>
  )

}

Home.layout = GeneralLayout;
export default Home;